# Generated by Django 3.2.3 on 2021-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0013_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
