# Generated by Django 3.2.3 on 2021-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0016_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
