# Generated by Django 3.2.3 on 2021-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0017_usercart_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
