# Generated by Django 3.2.3 on 2021-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0018_usercart_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='totalamount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
